/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:08e9e51b9c9d1ecfdce312b4ccaf09d5:ac7608d1f04ab193bff21724566c15eb:1a29484f10f40756034a0cb4556342aa$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class ShitGuy
	{
		public const string Background = "Background";
		public const string Default = "Default";
		public const string Shitguy_walk_0001 = "shitguy/walk/0001";
		public const string Shitguy_walk_0002 = "shitguy/walk/0002";
		public const string Shitguy_walk_0003 = "shitguy/walk/0003";
		public const string Shitguy_walk_0004 = "shitguy/walk/0004";

		// string[] Shitguy;


	}
}